server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Redireciona todas as rotas não encontradas para o index.html (necessário para SPA/Flutter Web)
        try_files $uri $uri/ /index.html;
    }
}
